version: "3.8"

services:

  server:
    depends_on:
      - db
    image: zawadbinsharif/mind-map-game:4.5-Production
    container_name: "conference_root_backend"
    build: ./
    ports:
      - 4000:4000
    env_file: .env
    networks:
      - conference-room-network
  
  db:
    image: mariadb
    restart: always
    ports:
      - 3308:3306
    environment:
      MARIADB_ROOT_PASSWORD: 1234
    volumes:
      - ./backup-volume:/backup
      - ./backup.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - conference-room-network

networks:
  conference-room-network:
    driver: bridge