version: "3.8"

services:

  server:
    depends_on:
      - db
    image: zawadbinsharif/mind-map-game:4.6-Production
    container_name: "conference_room_backend"
    ports:
      - 4000:4000
    env_file: .env
    volumes:
      - backup_of_conference_room:/app/backend/public/
    networks:
      - conference-room-network

  db:
    image: mariadb
    container_name: "conference_room_db"
    restart: always
    ports:
      - 3308:3306
    environment:
      MARIADB_ROOT_PASSWORD: 1234
    volumes:
      - db_backup_of_conference_room:/var/lib/mysql
    networks:
      - conference-room-network

networks:
  conference-room-network:
    driver: bridge

volumes:
  backup_of_conference_room:
  db_backup_of_conference_room:
